### ISSUE TITLE
Regarding API

### ISSUE THREAD

**Issue by manikasharma09** [shashank-sharma/django-dictionary#7]
I signed into oxford dictionary API and got only one credential there then where do i have to insert it in app id or app key

**Comment by shashank-sharma** [comment]
Hey @manikasharma09 Sorry for the late reply

If you can see this code: https://github.com/shashank-sharma/django-dictionary/blob/9ddc38e11ce8a89fe53f3cabb06765c5029b5a6a/dictionary/views.py#L54

There you need to replace APP_ID and APP_KEY with given config. In short you should define it as environment keys. Ideal case would be:

Create one .env file at root directory of django where manage.py is present and inside that file add all the Env keys over there as:

```
SECRET_KEY=asjdlkajdfksd
APP_ID=<app_id>
APP_KEY=<app_key>
```

Once all env keys are defined, you should import these settings in settings.py as:

`SECRET_KEY = os.environ['SECRET_KEY']
`

And then do same for app id and app key, once it is defined in code level, you can simply import from settings and use it inside views.py (which I mentioned in link)

Side note:

You can make use of this module which is pretty handy to use:

https://pypi.org/project/python-decouple/

Let me know if this solves your problem
Thanks

**Comment by manikasharma09** [comment]
Thankyou sir.
But sir actually what im asking is that on place of APP_ID do I have to insert the Credentials of the oxford API and in place of API_KEY do we have to insert the django app Secret key which is provided in seetings.py?

**Comment by shashank-sharma** [comment]
App key and Id both are related to Oxford api only, it's not related to django secret key

**Comment by manikasharma09** [comment]
![image](https://user-images.githubusercontent.com/51908554/81210771-fe064180-8fef-11ea-8d2e-d51df8e20aa2.png)
It is loading all the time and not showing the answer.
What can I do?

**Comment by shashank-sharma** [comment]
Since you are able to see words on left side, then api is working fine

Problem is that it is not able to show the description, most probably that particular code block is buggy

What you can try is to see how to use api to get description of any word and then see if you can solve that or not

Usually things changes time to time, maybe api return json structure is different now

I'll have a look too and see if I can solve this

**Comment by shashank-sharma** [comment]
@manikasharma09 So I tried out and for some reason I am quite irritated by oxford api let me share what I did:

Before I jump into, I want to tell that master code is all related to the deployment in heroku, hence for db, it will take from heroku psql url

1. Cloned and on starting I found secret key missing so resolved that
2. Migration not happening solved by: https://stackoverflow.com/a/26080380/3523510
3. Words are populated by dictionary.json file but oxford API was not working, in code I am using v1 of their API but within 2 year they updated their codebase to v2 hence look at API docs:

https://developer.oxforddictionaries.com/documentation

4. In Curl request by:
`
curl -X GET --header 'Accept: text/plain' --header 'app_id: <app_id>' --header 'app_key: <app_key>' 'https://od-api.oxforddictionaries.com/api/v2/entries/en-gb/ace?strictMatch=false'`

for some reason I am getting authentication error, you can try it out and see if it is working or not, else I'll suggest you to find any other API provider or create your own scrapper (maybe using wikipedia) or using wikipedia API and then implement it

So yes these are the things which I observed, in short oxford api one is no longer working in my case, let me know if you need help with anything else but I won't be updating the codebase right now

Example of what I faced:

![image12](https://user-images.githubusercontent.com/9320644/81827794-bedb7180-9556-11ea-8c23-666bccfd1e3d.png)

**Comment by manikasharma09** [comment]
Thank You @shashank-sharma.
 Yes , I tried changing the things after looking at the API documentation but things aren't working now also. It will be very helpful of you if you suggest me some other API provider .

**Comment by shashank-sharma** [comment]
@manikasharma09 This is what I came up with:

Wiktionary is really great place for open source dictionary content by Wikimedia foundation so here is what you can do:

1. [Optional]: To check if text (word) exist or not, you can make use of this: 
https://en.wiktionary.org/w/api.php?action=query&titles=ball&format=json

This return pageid if it exist else it gives -1

2. You can even search for any word by url:
https://en.wiktionary.org/w/index.php?title=ball&printable=yes

Here title=<word> is where you will type your word and search, if you are familiar with requests library and beautifulSoup then you can easily scrape given response which is in HTML and get meaningful result

3. If you want to save time, then maybe use someone else code, who has already done the heavy lifting for you so that you don't have to re-invent it
https://github.com/Suyash458/WiktionaryParser

Here you can read his docs and figure out how to work

4. Or you can take the dump and use it (which is heavy)
https://dumps.wikimedia.org/enwiktionary/latest/

[Source]: https://stackoverflow.com/questions/2770547/how-to-retrieve-wiktionary-word-content

Let me know if you face any problem with it
